Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AddressManager.Data;
using AddressManager.Models;

namespace AddressManager.Controllers
{
    public class UsersController : Controller
    {
        private readonly AddressManagerContext _context;
        private readonly ILogger<UsersController> _logger;

        public UsersController(AddressManagerContext context, ILogger<UsersController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            int userId = HttpContext.Session.GetInt32("userId") ?? 0;
            if (userId == 0)
            {
                return Redirect("/");
            }

            return _context.User != null ? 
                          View(await _context.User.ToListAsync()) :
                          Problem("Entity set 'AddressManagerContext.User'  is null.");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            int userId = HttpContext.Session.GetInt32("userId") ?? 0;
            if (userId == 0)
            {
                return Redirect("/");
            }

            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LoginId,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login", "Home");
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LoginId,Password")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.User == null)
            {
                return Problem("Entity set 'AddressManagerContext.User'  is null.");
            }
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.User?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AddressManager.Data;
using AddressManager.Models;
using Microsoft.Data.SqlClient;
using System.Configuration;
using AddressManager.Models.Pages;
using NuGet.Protocol;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Routing;
using System.Data;

namespace AddressManager.Controllers
{
    public class WorkersController : Controller
    {
        private readonly AddressManagerContext _context;
        private readonly ILogger<WorkersController> _logger;
        private readonly IConfiguration Configuration;

        public WorkersController(AddressManagerContext context, ILogger<WorkersController> logger, IConfiguration configuration)
        {
            _context = context;
            _logger = logger;
            Configuration = configuration;
        }

        // GET: Workers
        public async Task<IActionResult> Index(string ? columnName, string currentFilter, string searchString, int? pageIndex)
        {
            var pageSize = Configuration.GetValue("PageSize", 20);
            ViewBag.pagePerView = Configuration.GetValue("pagePerView", 20);

            // 검색조건 콤보박스
            var excludedColumns = new List<string> { "Id", "IsDelete" };
            var columns = _context.Model.FindEntityType(typeof(Worker)).GetProperties()
                .Where(p => !excludedColumns.Contains(p.GetColumnName()))
                .Select(p => p.GetColumnName()) // 컬럼명 가져오기
                .ToList();

            if (columnName != null)
            {
                ViewBag.Columns = new SelectList(columns, columnName);
            }
            else
            {
                ViewBag.Columns = new SelectList(columns);
            }

            // 검색어가 있으면
            if (!searchString.IsNullOrEmpty())
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            @ViewData["CurrentColumnFilter"] = columnName;
            ViewData["CurrentFilter"] = searchString;

            var workers = _context.Worker.Include(w => w.Company)
                                                    .Where(w => w.IsDelete == "N");
            // 검색조건과 검색어를 리스트에 반영
            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(columnName))
            {
                switch (columnName)
                {
                    case "CompanyId":
                        workers = workers.Where(s => s.Company.Name.Contains(searchString));
                        break;
                    case "Name":
                        workers = workers.Where(s => s.Name.Contains(searchString));
                        break;
                    case "Email":
                        workers = workers.Where(s => s.Email.Contains(searchString));
                        break;
                    case "Phone":
                        workers = workers.Where(s => s.Phone.Contains(searchString));
                        break;
                }
                _logger.LogInformation($"In Deleted Companies Page - search condition = {columnName}, search word = {searchString}");
            }

            return _context.Worker != null ?
                          View(await Pagination<Worker>
                          .CreateAsync(workers.OrderBy(c => c.Id).AsNoTracking(), pageIndex ?? 1, pageSize))
                          : Problem("Entity set 'AddressManagerContext.Worker'  is null.");
        }

        // GET: Workers
        public async Task<IActionResult> DelList(string? columnName, string currentFilter, string searchString, int? pageIndex)
        {
            int userId = HttpContext.Session.GetInt32("userId") ?? 0;
            if (userId == 0)
            {
                return Redirect("/");
            }

            var pageSize = Configuration.GetValue("PageSize", 20);
            ViewBag.pagePerView = Configuration.GetValue("pagePerView", 20);

            // 검색조건 콤보박스
            var excludedColumns = new List<string> { "Id", "IsDelete" };
            var columns = _context.Model.FindEntityType(typeof(Worker)).GetProperties()
                .Where(p => !excludedColumns.Contains(p.GetColumnName()))
                .Select(p => p.GetColumnName()) // 컬럼명 가져오기
                .ToList();

            if (columnName != null)
            {
                ViewBag.Columns = new SelectList(columns, columnName);
            }
            else
            {
                ViewBag.Columns = new SelectList(columns);
            }

            // 검색어가 있으면
            if (!searchString.IsNullOrEmpty())
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            @ViewData["CurrentColumnFilter"] = columnName;
            ViewData["CurrentFilter"] = searchString;

            var workers = _context.Worker.Include(w => w.Company)
                                                    .Where(w => w.IsDelete == "Y");

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(columnName))
            {
                switch (columnName)
                {
                    case "CompanyId":
                        workers = workers.Where(s => s.Company.Name.Contains(searchString));
                        break;
                    case "Name":
                        workers = workers.Where(s => s.Name.Contains(searchString));
                        break;
                    case "Email":
                        workers = workers.Where(s => s.Email.Contains(searchString));
                        break;
                    case "Phone":
                        workers = workers.Where(s => s.Phone.Contains(searchString));
                        break;
                }
                _logger.LogInformation($"In Deleted Workers Page - search condition = {columnName}, search word = {searchString}");
            }

            return _context.Worker != null ?
                          View(await Pagination<Worker>
                          .CreateAsync(workers.OrderBy(c => c.Id).AsNoTracking(), pageIndex ?? 1, pageSize))
                          : Problem("Entity set 'AddressManagerContext.Worker'  is null.");
        }

        // GET: Workers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            int userId = HttpContext.Session.GetInt32("userId") ?? 0;
            if (userId == 0)
            {
                return Redirect("/");
            }

            if (id == null || _context.Worker == null)
            {
                return NotFound();
            }

            var worker = await _context.Worker
                .Include(w => w.Company)
                .FirstOrDefaultAsync(w => w.Id == id);
            if (worker == null)
            {
                return NotFound();
            }
           var change = await _context.ChangeHistory.Where(h => h.WorkerId == id).ToListAsync() ;
            var tuple = (Worker: worker, ChangeHistory:change);
            return View(tuple);
        }

        // GET: Workers/Create
        public IActionResult Create()
        {
            int userId = HttpContext.Session.GetInt32("userId") ?? 0;
            if (userId == 0)
            {
                return Redirect("/");
            }

            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Name");
            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyId,Name,Email,Phone, Company")] Worker worker)
        {
            int userId = HttpContext.Session.GetInt32("userId") ?? 0;
            string? userLoginId = HttpContext.Session.GetString("userLoginId");

            if (userId != 0 && userLoginId != null)
            {
                var p1 = new SqlParameter("@CompanyId", worker.CompanyId);
                var p2 = new SqlParameter("@Name", worker.Name);
                var p3 = new SqlParameter("@Email", worker.Email);
                var p4 = new SqlParameter("@Phone", worker.Phone);
                var p5 = new SqlParameter("@UserId", userId);
                var p6 = new SqlParameter("@LoginId", userLoginId);
                var p7 = new SqlParameter("@ActIP", HttpContext.Connection.RemoteIpAddress?.ToString() ?? string.Empty);

                string query = @"EXEC CreateWorker @CompanyId, @Name, @Email, @Phone, @UserId, @LoginId, @ActIP";
                await _context.Database.ExecuteSqlRawAsync(query, p1, p2, p3, p4, p5, p6, p7);

                _logger.Log(LogLevel.Information,
                    $"delete company => UserId = {p5.SqlValue}, UserLoginId = {p6.SqlValue}, " +
                    $"target = Worker, CompanyId ={p1.SqlValue}, WorkerName = {p2.SqlValue} IP = {p7.SqlValue}, time = {DateTime.Now}");

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Company, "Id", "Address", worker.CompanyId);
            return View(worker);
        }

        // GET: Workers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Worker == null)
            {
                return NotFound();
            }

            var worker = await _context.Worker.FindAsync(id);
            if (worker == null)
            {
                return NotFound();
            }

Views/Shared/_Layout.cshtml
@{
    bool isLogin = false;
    if (Context.Session.GetInt32("userId") != null)
    {
        isLogin = true;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AddressManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AddressManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Company List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Index">Worker List</a>
                        </li>
                        @{
                            if (isLogin){     
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="DelList">Deleted Companies</a>
                            </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="DelList">Deleted Workers</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <div align="right" style="display:flex">
                    @{
                        string Login = "Login";
                        if (isLogin)
                        {
                            Login = "Logout";
                            var userPk = @Context.Session.GetInt32("userId");
                            var userId = @Context.Session.GetString("userLoginId");
                            <span class="nav-link text-dark">Id  -  <span style="font-weight:bold">@userId</span></span>
                        }
                        else
                        {
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">sign in</a>
                        }
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="@Login">@Login</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AddressManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>